# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1


- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

#Build project. 
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

#Run Unit Tests
- script: dotnet test --configuration $(buildConfiguration)
  displayName: 'dotnet test $(buildConfiguration)'

#Pack to a nuget package
- task: DotNetCoreCLI@2
  displayName: "dotnet pack"
  inputs:
    command: 'pack'
    arguments: '--configuration $(buildConfiguration)'
    packagesToPack: 'MottMacdonald.Core/*.csproj'
    nobuild: true
    versioningScheme: 'off'

#Push nuget package to feed. 

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '4768ba56-4612-49bf-b4ec-a486631ca039/d7726ced-6244-4c4b-8e8e-b4888dca8f85'
    versioningScheme: 'off'
    allowPackageConflicts: true
